networks:
  loki-nginx-network:
    external: false


services:
  nginx-service:
    image: nginx:1.23.4-alpine
    container_name: nginx-service
    networks:
      - loki-nginx-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./nginx/nginx-stub-status.conf:/etc/nginx/conf.d/nginx-stub-status.conf:ro
      - ./logs:/var/log/nginx # 将 Nginx 容器日志映射到本地磁盘
    ports:
      - "8080:8080"
    environment:
      # 设置中国时区
      TZ: Asia/Shanghai

  # Grafana
  # 默认端口 3000
  grafana-service:
    image: grafana/grafana:11.3.2-ubuntu
    container_name: grafana-service
    networks:
      - loki-nginx-network
    ports:
      - "9000:3000"
    volumes:
      - ./grafana/provisioning/etc/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/etc/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      # 中国时区
      TZ: Asia/Shanghai
      # 匿名登陆
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_ALLOW_SIGN_UP: false

  loki-service:
    image: grafana/loki:3.4
    container_name: loki-service
    networks:
      - loki-nginx-network
    ports:
      - "9001:3100"
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
    environment:
      # 中国时区
      TZ: Asia/Shanghai
    command:
      - "--config.file=/etc/loki/config.yaml"

  promtail-service:
    image: grafana/promtail:3.4
    container_name: promtail-service
    volumes:
      # 设置目录挂载
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro
      - ./logs:/var/log
    environment:
      TZ: Asia/Shanghai
    networks:
      - loki-nginx-network
    command:
      - "--config.file=/etc/promtail/promtail.yaml" # promtail配置文件
    depends_on:
      - loki-service

